# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/chin39/Dropbox/RPI/Intro to Info Sec/SecureCoding"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/chin39/Dropbox/RPI/Intro to Info Sec/SecureCoding"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/chin39/Dropbox/RPI/Intro to Info Sec/SecureCoding/CMakeFiles" "/Users/chin39/Dropbox/RPI/Intro to Info Sec/SecureCoding/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/chin39/Dropbox/RPI/Intro to Info Sec/SecureCoding/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named daytime

# Build rule for target.
daytime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daytime
.PHONY : daytime

# fast build rule for target.
daytime/fast:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/build
.PHONY : daytime/fast

#=============================================================================
# Target rules for targets named daytimed

# Build rule for target.
daytimed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daytimed
.PHONY : daytimed

# fast build rule for target.
daytimed/fast:
	$(MAKE) -f CMakeFiles/daytimed.dir/build.make CMakeFiles/daytimed.dir/build
.PHONY : daytimed/fast

#=============================================================================
# Target rules for targets named echo

# Build rule for target.
echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo
.PHONY : echo

# fast build rule for target.
echo/fast:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/build
.PHONY : echo/fast

#=============================================================================
# Target rules for targets named echod

# Build rule for target.
echod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echod
.PHONY : echod

# fast build rule for target.
echod/fast:
	$(MAKE) -f CMakeFiles/echod.dir/build.make CMakeFiles/echod.dir/build
.PHONY : echod/fast

daytime.o: daytime.c.o

.PHONY : daytime.o

# target to build an object file
daytime.c.o:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.c.o
.PHONY : daytime.c.o

daytime.i: daytime.c.i

.PHONY : daytime.i

# target to preprocess a source file
daytime.c.i:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.c.i
.PHONY : daytime.c.i

daytime.s: daytime.c.s

.PHONY : daytime.s

# target to generate assembly for a file
daytime.c.s:
	$(MAKE) -f CMakeFiles/daytime.dir/build.make CMakeFiles/daytime.dir/daytime.c.s
.PHONY : daytime.c.s

daytimed.o: daytimed.c.o

.PHONY : daytimed.o

# target to build an object file
daytimed.c.o:
	$(MAKE) -f CMakeFiles/daytimed.dir/build.make CMakeFiles/daytimed.dir/daytimed.c.o
.PHONY : daytimed.c.o

daytimed.i: daytimed.c.i

.PHONY : daytimed.i

# target to preprocess a source file
daytimed.c.i:
	$(MAKE) -f CMakeFiles/daytimed.dir/build.make CMakeFiles/daytimed.dir/daytimed.c.i
.PHONY : daytimed.c.i

daytimed.s: daytimed.c.s

.PHONY : daytimed.s

# target to generate assembly for a file
daytimed.c.s:
	$(MAKE) -f CMakeFiles/daytimed.dir/build.make CMakeFiles/daytimed.dir/daytimed.c.s
.PHONY : daytimed.c.s

echo.o: echo.c.o

.PHONY : echo.o

# target to build an object file
echo.c.o:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.c.o
.PHONY : echo.c.o

echo.i: echo.c.i

.PHONY : echo.i

# target to preprocess a source file
echo.c.i:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.c.i
.PHONY : echo.c.i

echo.s: echo.c.s

.PHONY : echo.s

# target to generate assembly for a file
echo.c.s:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.c.s
.PHONY : echo.c.s

echod.o: echod.c.o

.PHONY : echod.o

# target to build an object file
echod.c.o:
	$(MAKE) -f CMakeFiles/echod.dir/build.make CMakeFiles/echod.dir/echod.c.o
.PHONY : echod.c.o

echod.i: echod.c.i

.PHONY : echod.i

# target to preprocess a source file
echod.c.i:
	$(MAKE) -f CMakeFiles/echod.dir/build.make CMakeFiles/echod.dir/echod.c.i
.PHONY : echod.c.i

echod.s: echod.c.s

.PHONY : echod.s

# target to generate assembly for a file
echod.c.s:
	$(MAKE) -f CMakeFiles/echod.dir/build.make CMakeFiles/echod.dir/echod.c.s
.PHONY : echod.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... daytime"
	@echo "... daytimed"
	@echo "... echo"
	@echo "... edit_cache"
	@echo "... echod"
	@echo "... daytime.o"
	@echo "... daytime.i"
	@echo "... daytime.s"
	@echo "... daytimed.o"
	@echo "... daytimed.i"
	@echo "... daytimed.s"
	@echo "... echo.o"
	@echo "... echo.i"
	@echo "... echo.s"
	@echo "... echod.o"
	@echo "... echod.i"
	@echo "... echod.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

